### ISSUE TITLE
Does it work in github page?

### ISSUE THREAD

**Issue by xcTorres** [ggreer/jekyll-gallery-generator#44]

**Comment by gertoe** [comment]
Since `jekyll-gallery-generator` depends on imagagemagick for the image conversion, and GitHub only allows a subset of Jekyll plugins within their compilation pipeline, this plugin should not work with GitHub Pages (cf. [jekyllrb.com](https://jekyllrb.com/docs/github-pages/)). However, to deploy your page to GitHub, you still can compile your site locally before pushing, though.

**Comment by xcTorres** [comment]
Thanks for your reply. It works when I compile the site locally and push the site files into another branch.    

BTW is there anyone that wants to add this awesome gallery plugin in your GitHub page, you could refer to this link.
https://surdu.me/2020/02/04/jekyll-git-hook.html.  

In this link, you could copy the git hook script so that it doesn't take too much effort to check out the new branch.

**Comment by eoli3n** [comment]
Here what I adapted to get your link fully working : https://github.com/eoli3n/eoli3n.github.io#install
